VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE = "ubuntu/focal64"
NODE_COUNT = 3
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "web#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "web#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      'modifyvm', :id,
      '--natdnshostresolver1', 'on',
      '--memory', '512',
      '--cpus', '1'
    ]
  end
end


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "db#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "db#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 20}"
    end
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      'modifyvm', :id,
      '--natdnshostresolver1', 'on',
      '--memory', '512',
      '--cpus', '1'
    ]
  end
end