VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE = "ubuntu/focal64"
NODE_COUNT = 1
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "node1" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node1"
      subconfig.vm.network :private_network, ip: "192.168.56.7"
    end

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      'modifyvm', :id,
      '--natdnshostresolver1', 'on',
      '--memory', '512',
      '--cpus', '1'
    ]
  end
end